import type { Metadata } from "next";
import "./globals.css";

// Google Fonts ke imports aur functions hata diye hain taake download error na aaye

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      {/* Humne variables hatakar standard font-sans use kar liya hai jo aapke Tailwind ke classes ko chalata rahega */}
      <body className="min-h-full flex flex-col font-sans bg-white dark:bg-black text-black dark:text-zinc-50">
        {children}
      </body>
    </html>
  );
}